### ISSUE TITLE
GPUs to Train the Model 

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [RaymondLZhou/deepDeband#2]
Hi!
Would like to know the number of GPUs being used in the original paper, thanks a lot.

**Comment by RaymondLZhou** [comment]
It was trained on 2 GPUs

**Comment by FireWallDragonDarkFluid** [comment]
Thanks for the kind reply, what're the type of the GPUs, A100?

**Comment by RaymondLZhou** [comment]
They were P100 GPUs
