### ISSUE TITLE
No way to evaluate

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [RaymondLZhou/deepDeband#3]
As the dataset only contains image patches, it seems that there is no way to evaluate the model, am I correct?

Can the full size (1920x1080) FHD images be accessed? Thanks a lot.

**Comment by RaymondLZhou** [comment]
I'll see if I can find the FHD image set to upload - you're right that the current one only has patches

**Comment by FireWallDragonDarkFluid** [comment]
Hi!
Thanks for the kind reply, any update?

**Comment by RaymondLZhou** [comment]
I couldn't find it locally on my end, but the set of all FHD images were taken from here: https://github.com/akshay-kap/Meng-699-Image-Banding-detection
