### ISSUE TITLE
Checkpoints not available

### ISSUE THREAD

**Issue by remg1997** [RaymondLZhou/deepDeband#6]
Hey there! Trying to use deepDeband, but when cloning I get the following error:

`Smudge error: Error downloading pytorch-CycleGAN-and-pix2pix/checkpoints/deepDeband-f/latest_net_D.pth (913559ab218f4acb5c46e3f1a3b4b3622c877ae953e3c206673cb6855a972b59): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Any way you can make this available again?

**Comment by RaymondLZhou** [comment]
You can also download it from the Zenodo link here: https://github.com/RaymondLZhou/deepDeband#model
